#!/bin/bash
# Generated by pde2tycho. Starts the product with plain java; the product has no native launcher.

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Inside a materialized product plugins/ sits next to this script. From the source tree
# (distribution/scripts/) use the product the build produced for this OS and CPU.
if [ -d "$SCRIPT_DIR/plugins" ]; then
    PRODUCT_DIR="$SCRIPT_DIR"
else
    PRODUCTS="$(cd "$SCRIPT_DIR/.." && pwd)/target/products/@PRODUCT_ID@"
    ARCH="$(uname -m)"
    [ "$ARCH" = "arm64" ] && ARCH="aarch64"
    case "$(uname -s)" in
@OS_CASES@        *)
            echo "ERROR: No product was built for $(uname -s). On Windows use run.bat."
            exit 1
            ;;
    esac
fi

OSGI_JAR=$(ls "$PRODUCT_DIR/plugins/org.eclipse.osgi_"*.jar 2>/dev/null | head -1)
if [ -z "$OSGI_JAR" ]; then
    echo "ERROR: Could not find org.eclipse.osgi jar in: $PRODUCT_DIR/plugins/"
    echo "Hint: run 'mvn clean verify' from the project root first."
    exit 1
fi

echo "Starting OSGi framework: $OSGI_JAR"
cd "$PRODUCT_DIR"
# "$@" carries caller -D flags; they must precede -jar to reach the JVM as system properties.
exec java @VM_ARGS@ "$@" -jar "$OSGI_JAR" -configuration configuration -console @PROGRAM_ARGS@
