@echo off
rem Generated by pde2tycho. Starts the product with plain java; the product has no native launcher.
setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"

rem Inside a materialized product plugins\ sits next to this script. From the source tree
rem (distribution\scripts\) use the Windows product the build produced.
if exist "%SCRIPT_DIR%\plugins\" (
    set "PRODUCT_DIR=%SCRIPT_DIR%"
) else (
    for %%A in ("%SCRIPT_DIR%\..") do set "BASE_DIR=%%~fA"
    set "PRODUCT_DIR=!BASE_DIR!\target\products\@PRODUCT_ID@\win32\win32\x86_64"
)

for %%f in ("!PRODUCT_DIR!\plugins\org.eclipse.osgi_*.jar") do set "OSGI_JAR=%%f"
if not defined OSGI_JAR (
    echo ERROR: Could not find org.eclipse.osgi jar in: !PRODUCT_DIR!\plugins\
    echo Hint: run "mvn clean verify" from the project root first.
    exit /b 1
)

echo Starting OSGi framework: !OSGI_JAR!
cd /d "!PRODUCT_DIR!"
rem %* carries caller -D flags; they must precede -jar to reach the JVM as system properties.
java @VM_ARGS@ %* -jar "!OSGI_JAR!" -configuration configuration -console @PROGRAM_ARGS@
